modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="arrowverse"
version="1.0.0"
displayName="ArrowverseCore"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="allanep9, MCreator"

[[dependencies.arrowverse]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



